### ISSUE TITLE
I wonder if you could help me write the reflection of the e-learning……800+ words

### ISSUE THREAD

**Issue by FanxingTree** [herobrine1010/Party-Lecture-Cracker#3]

**Comment by herobrine1010** [comment]
You may have a glance to [this project](https://suulnnka.github.io/BullshitGenerator/index.html?%E4%B8%BB%E9%A2%98=%E5%8A%AA%E5%8A%9B%E6%88%90%E4%B8%BA%E5%85%A5%E5%85%9A%E7%A7%AF%E6%9E%81%E5%88%86%E5%AD%90&%E9%9A%8F%E6%9C%BA%E7%A7%8D%E5%AD%90=1264967258).
